#!/bin/bash
set -e

pkg=sortedcollections

if [ "${AUTOPKGTEST_TMP}" = "" ] ; then
  AUTOPKGTEST_TMP=$(mktemp -d /tmp/${pkg}-test.XXXXXX)
  trap "rm -rf ${AUTOPKGTEST_TMP}" 0 INT QUIT ABRT PIPE TERM
fi

cp -ar tests/ "${AUTOPKGTEST_TMP}"

cd "${AUTOPKGTEST_TMP}"
py.test-3
